# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.cache/wt [current_project]
set_property parent.project_path C:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/hdl/design_dma_sg_wrapper.vhd
add_files C:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/design_dma_sg.bd
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_processing_system7_0_0/design_dma_sg_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_axi_dma_0_0/design_dma_sg_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_axi_dma_0_0/design_dma_sg_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_axi_dma_0_0/design_dma_sg_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_rst_ps7_0_100M_0/design_dma_sg_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_rst_ps7_0_100M_0/design_dma_sg_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_rst_ps7_0_100M_0/design_dma_sg_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_axis_data_fifo_0_0/design_dma_sg_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_axis_data_fifo_0_0/design_dma_sg_axis_data_fifo_0_0/design_dma_sg_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_xbar_0/design_dma_sg_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_auto_pc_0/design_dma_sg_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_auto_pc_1/design_dma_sg_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_auto_us_0/design_dma_sg_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_auto_us_0/design_dma_sg_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_auto_us_1/design_dma_sg_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_auto_us_1/design_dma_sg_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_auto_us_2/design_dma_sg_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/ip/design_dma_sg_auto_us_2/design_dma_sg_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/design_dma_sg_ooc.xdc]
set_property is_locked true [get_files C:/Users/kab/Desktop/workspace/dma_sg_prj/dma_sg_prj.srcs/sources_1/bd/design_dma_sg/design_dma_sg.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_dma_sg_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_dma_sg_wrapper.dcp

catch { report_utilization -file design_dma_sg_wrapper_utilization_synth.rpt -pb design_dma_sg_wrapper_utilization_synth.pb }
