# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_dma_sg/design_dma_sg.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg || ORIG_REF_NAME==design_dma_sg}]

# IP: bd/design_dma_sg/ip/design_dma_sg_processing_system7_0_0/design_dma_sg_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_processing_system7_0_0 || ORIG_REF_NAME==design_dma_sg_processing_system7_0_0}]

# IP: bd/design_dma_sg/ip/design_dma_sg_axi_dma_0_0/design_dma_sg_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_axi_dma_0_0 || ORIG_REF_NAME==design_dma_sg_axi_dma_0_0}]

# IP: bd/design_dma_sg/ip/design_dma_sg_ps7_0_axi_periph_0/design_dma_sg_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_dma_sg_ps7_0_axi_periph_0}]

# IP: bd/design_dma_sg/ip/design_dma_sg_rst_ps7_0_100M_0/design_dma_sg_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_dma_sg_rst_ps7_0_100M_0}]

# IP: bd/design_dma_sg/ip/design_dma_sg_axis_data_fifo_0_0/design_dma_sg_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_axis_data_fifo_0_0 || ORIG_REF_NAME==design_dma_sg_axis_data_fifo_0_0}]

# IP: bd/design_dma_sg/ip/design_dma_sg_axi_mem_intercon_0/design_dma_sg_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_axi_mem_intercon_0 || ORIG_REF_NAME==design_dma_sg_axi_mem_intercon_0}]

# IP: bd/design_dma_sg/ip/design_dma_sg_xbar_0/design_dma_sg_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_xbar_0 || ORIG_REF_NAME==design_dma_sg_xbar_0}]

# IP: bd/design_dma_sg/ip/design_dma_sg_xlconcat_0_0/design_dma_sg_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_xlconcat_0_0 || ORIG_REF_NAME==design_dma_sg_xlconcat_0_0}]

# IP: bd/design_dma_sg/ip/design_dma_sg_auto_pc_0/design_dma_sg_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_auto_pc_0 || ORIG_REF_NAME==design_dma_sg_auto_pc_0}]

# IP: bd/design_dma_sg/ip/design_dma_sg_auto_pc_1/design_dma_sg_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_auto_pc_1 || ORIG_REF_NAME==design_dma_sg_auto_pc_1}]

# IP: bd/design_dma_sg/ip/design_dma_sg_auto_us_0/design_dma_sg_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_auto_us_0 || ORIG_REF_NAME==design_dma_sg_auto_us_0}]

# IP: bd/design_dma_sg/ip/design_dma_sg_auto_us_1/design_dma_sg_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_auto_us_1 || ORIG_REF_NAME==design_dma_sg_auto_us_1}]

# IP: bd/design_dma_sg/ip/design_dma_sg_auto_us_2/design_dma_sg_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_sg_auto_us_2 || ORIG_REF_NAME==design_dma_sg_auto_us_2}]

# XDC: bd/design_dma_sg/design_dma_sg_ooc.xdc
